name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lint.yaml'
      - 'risken-mcp-server/cmd/**'
      - 'risken-mcp-server/pkg/**'
      - 'risken-mcp-server/go.*'
      - 'risken-mcp-server/.golangci.yml'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.5.2
        with:
          version: v1.62.0
