name: Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/push.yaml'
      - 'risken-mcp-server/cmd/**'
      - 'risken-mcp-server/pkg/**'
      - 'risken-mcp-server/go.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ca-risken/risken-mcp-server:latest
            ghcr.io/ca-risken/risken-mcp-server:${{ github.sha }}
